point_table = "Paper"
area_table = "Plain"
displaycategory = "Standard,Other"
debug = false
excluded_lookups = ["M_QUAL","LNDARE","LNDRGN","BUAARE","RIVERS","LAKARE","LIGHTS"]

[paths]
chartsymbols = "../chart-installation/generate_map_files/resources/chartsymbols/chartsymbols_S57.xml"
ruleset = "../chart-installation/generate_map_files/resources/rules"
chart = "../noaa_enc/ENC_ROOT"
data = "../noaa_enc/generated/shp"
map = "../noaa_enc/generated/map"
