point_table = "Paper"
area_table = "Plain"
displaycategory = "Standard,Other"
debug = false
excluded_lookups = ["LIGHTS"]

[paths]
chartsymbols = "../chart-installation/generate_map_files/resources/chartsymbols/chartsymbols_S57.xml"
ruleset = "../chart-installation/generate_map_files/resources/rules"
chart = "/data/ENC_ROOT"
data = "/data/generated/shp"
map = "/data/generated/map"
