point_table = "Paper"
area_table = "Plain"
displaycategory = "Standard,Other"
debug = false
excluded_lookups = ["LIGHTS"]
excluded_lookup_labels = ["BCNCAR","BCNISD","BCNLAT","BCNSAW","BCNSPP","BOYCAR","BOYINB","BOYISD","BOYLAT","BOYSAW","BOYSPP","BRIDGE","FOGSIG","LIGHTS","RADRNG","RADSTA","RDOCAL","RDOSTA","RTPBCN"]

[paths]
chartsymbols = "../chart-installation/generate_map_files/resources/chartsymbols/chartsymbols_S57.xml"
ruleset = "../chart-installation/generate_map_files/resources/rules"
chart = "/data/ENC_ROOT"
data = "/data/generated/shp"
map = "/data/generated/map"
