point_table = "Paper"
area_table = "Plain"
displaycategory = "Standard,Other"
debug = false
excluded_lookups = ["M_QUAL","LNDRGN","BUAARE","RIVERS","LAKARE","LIGHTS"]
excluded_lookup_labels = ["BCNCAR","BCNISD","BCNLAT","BCNSAW","BCNSPP","BOYCAR","BOYINB","BOYISD","BOYLAT","BOYSAW","BOYSPP","BRIDGE","FOGSIG","LNDARE","LIGHTS","RADRNG","RADSTA","RDOCAL","RDOSTA","RTPBCN"]
layer_groups_to_keep = ["LAND","BRIDGES","DEPTHS","SEABED","SIGNALS","SPECIAL"]

[paths]
chartsymbols = "../chart-installation/generate_map_files/resources/chartsymbols/chartsymbols_S57.xml"
ruleset = "../chart-installation/generate_map_files/resources/rules"
chart = "/data/ENC_ROOT"
data = "/data/generated/shp"
map = "/data/generated/map"
